### ISSUE TITLE
Tiddler's Name in Table-of-Contents Macros Not Updated

### ISSUE THREAD

**Issue by shandow856** [flibbles/tw5-relink#16] opened 2020-05-08 13:02 UTC
This is my first time to report an issue so please excuse me if there's anything unclear. 

I have the 1.91 version Relink installed in an empty TiddlyWiki file. I create a tiddler named "**New Tiddler**", tag it with `$:/tags/SideBar` and use macros to make a table of content in the tiddler: 

`<div class="tc-table-of-contents">`
`<<toc-selective-expandable 'New Tiddler' sort[title]>>`
`</div>`

But the tiddler's name in the macros does not get updated when I rename this tiddler. Whereas this tiddler's name in another tiddler's tag field gets updated. Is it something that needs to be fixed? Thanks. 

![relink issue](https://user-images.githubusercontent.com/58639807/81407265-a857a380-916d-11ea-9627-f79c73f975b2.png)

**Comment by flibbles** [comment] 2020-05-08 14:05
Hi. Thanks for reporting this!

The problem is that the toc-* school of macros didn't have a default configuration plugged in. This is now fixed in 1.9.2. You can see their configuration in the macro whitelist table:

![whitelist](https://user-images.githubusercontent.com/205465/81413257-1de25600-9113-11ea-8f7e-7df000059349.png)

If for whatever reason you're not able to update to 1.9.2, you can always manually add their macro parameter yourself. (But no one should have to.)

**Closed by flibbles** 2020-05-08 14:05 UTC
