### ISSUE TITLE
Error relinking a title with a path separator.

### ISSUE THREAD

**Issue by joshuafontany** [flibbles/tw5-relink#17] opened 2020-05-08 23:13 UTC
I'm not 100% that is the root cause of this, but it mainly seems to happen when I have a path separator in the title and try to change it in any way (with or without the rename checkbox checked).

TW5.1.23-pre, running Node.js on Win10

The only other plugin I have loaded is: $:/plugins/wikilabs/uni-link

I am using $:/config/FileSystemPaths

Error screenshots attached.

Best,
Josh F
![flibbles_relink_error01](https://user-images.githubusercontent.com/9102855/81456369-e68d9c80-9146-11ea-8039-542352eb1675.png)
![flibbles_relink_error02](https://user-images.githubusercontent.com/9102855/81456370-e7bec980-9146-11ea-8098-60da76f6ccda.png)

**Comment by flibbles** [comment] 2020-05-09 00:35
Turns out this is a problem with how Relink and Uni-link interact with each other.

The problem was caused by me, but technically the fix is better done in Uni-link.

[I've submitted and issue with them detailing what to do.](https://github.com/wikilabs/plugins/issues/46) If Mario (unilink creator) doesn't get a change out soon, I can make a workaround in Relink.

**Comment by flibbles** [comment] 2020-05-09 00:36
(...seeing as how this is originally my fault for making a backward incompatible change)

**Comment by joshuafontany** [comment] 2020-05-09 02:17
Mahalo (thanks)!

**Comment by flibbles** [comment] 2020-05-09 03:01
Glad my fix works. Hopefully Mario will get that change in, so you won't have to have an overridden shadow tiddler. I'll leave this open in the meantime.

And Mario, if you're reading this. Sorry about putting this fix on you, seeing as how it was my change to my own code that broke stuff.

**Comment by flibbles** [comment] 2020-06-15 14:47
I'm going to close this on my end, since there's nothing more that I can do. This problem will fix once the issue I submitted on Uni-Link is resolved.

**Closed by flibbles** 2020-06-15 14:47 UTC
